---
title: "Impact of coverage for Pilon error correction"
date: "`r Sys.Date()`"
author: "Ben Temperton"
output:
  rmdformats::readthedown:
    highlight: kate
bibliography: bibliography.bib
csl: the-isme-journal.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(cowplot)
library(ggsci)
library(magrittr)
source('useful.functions.R')
```

# Load data
```{r, warning=FALSE, message=FALSE}
df<-read_csv('./data/combined.pilon.correct.csv.gz')
```

# Evaluate total snps
```{r}
summary_df <- df %>% group_by(tot_gigabases, seed) %>% summarise(total_corrected_snps=sum(snps), 
                                                      total_fixed_insertions=sum(fixed_insertions),
                                                      total_fixed_deletions=sum(fixed_deletions),
                                                      median_coverage=median(coverage),)
tara_mean_bp=8901634615/1e9

tmp<-summary_df %>% gather(key='count_type', value='count', median_coverage, total_fixed_insertions, total_fixed_deletions, total_corrected_snps)
tmp$count_type<-as.factor(tmp$count_type)
levels(tmp$count_type)<-c( 'Median Coverage','Total corrected SNPS','Total Fixed Deletions', 'Total Fixed Insertions')
ggplot(tmp, aes(x=tot_gigabases, y=count)) + 
  geom_point(size=3, alpha=0.4, pch=21, color='black', fill='blue') + 
  facet_wrap(~count_type, nrow=2, ncol=2, scales='free_y') +
  labs(x='Gbp of short-read data mapped to Pilon contigs',
       y='Count',
       caption='Dashed line represents mean size of Global Ocean Virome Datasets')+
  geom_vline(xintercept=tara_mean_bp, linetype='dashed') +
  theme(legend.position='none',
        strip.background=element_rect(fill='white'),
        strip.text=element_text(face='bold', hjust=0, size=14),
        axis.title.x = element_text(size=14, face='bold'),
        axis.title.y = element_text(size=14, face='bold'),
        panel.spacing.y=unit(1.5, 'lines')) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 8))

```

```{r}

ggplot(df, aes(x=tot_gigabases, y=fixed_insertions, color=contig)) + 
  geom_line() +
  theme(legend.position='none',
        strip.background=element_rect(fill='white'),
        strip.text=element_text(face='bold', hjust=0, size=14),
        axis.title.x = element_text(size=14, face='bold'),
        axis.title.y = element_text(size=14, face='bold')) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 9))

```
